/* 
Fred O'Hara
Project 2
4/9/2016

Request 1
*/

CREATE TABLE EMPS
AS (SELECT *
    FROM EMPLOYEES
    WHERE employee_id != 178);
    
SELECT constraint_name, constraint_type, table_name, search_condition
FROM user_constraints
WHERE table_name = 'EMPS';

ALTER TABLE EMPS
ADD (CONSTRAINT EMPS_employee_id_pk PRIMARY KEY (employee_id),
    CONSTRAINT EMPS_department_fk FOREIGN KEY (department_id)
    REFERENCES DEPARTMENTS (department_id),
    CONSTRAINT EMPS_email_uq UNIQUE (EMAIL));
    
ALTER TABLE EMPS RENAME CONSTRAINT SYS_C00287350 TO LAST_NAME_NN;
ALTER TABLE EMPS RENAME CONSTRAINT SYS_C00287352 TO HIRE_DATE_NN;
ALTER TABLE EMPS RENAME CONSTRAINT SYS_C00287353 TO JOB_ID_NN;
    
ALTER TABLE EMPS
DROP CONSTRAINT SYS_C00287351;
    
ALTER TABLE EMPS
ADD (FULL_NAME VARCHAR(35));

UPDATE EMPS
SET FULL_NAME = (first_name||' '||last_name);

ALTER TABLE EMPS
MODIFY (FIRST_NAME NOT NULL,
        FULL_NAME NOT NULL);

/* 
Fred O'Hara
Project 2
4/9/2016

Request 2
*/  
      
SELECT EMPLOYEE_ID, FULL_NAME, SALARY, DEPARTMENT_ID
FROM EMPS
ORDER BY LAST_NAME DESC;

/* 
Fred O'Hara
Project 2
4/9/2016

Request 3
*/

CREATE VIEW SAL_DATA_BY_JOB_ID
AS (SELECT JOB_ID, AVG(SALARY) AS AVG_SAL, MAX(SALARY) AS MAX_SAL, 
    MIN(SALARY) AS MIN_SAL, MAX(SALARY) - MIN(SALARY) AS SAL_DIFF
    FROM EMPS
    GROUP BY JOB_ID);
    
SELECT * FROM SAL_DATA_BY_JOB_ID;

/* 
Fred O'Hara
Project 2
4/9/2016

Request 4
*/

SELECT e.EMPLOYEE_ID, e.FULL_NAME, m.FULL_NAME as MANAGER
FROM EMPS e
LEFT JOIN  EMPS m ON
m.EMPLOYEE_ID = e.MANAGER_ID
ORDER BY e.EMPLOYEE_ID; 

/* 
Fred O'Hara
Project 2
4/9/2016

Request 5
*/

CREATE TABLE DEPS AS (SELECT * FROM DEPARTMENTS);

ALTER TABLE DEPS
DROP CONSTRAINT SYS_C00287471;

ALTER TABLE DEPS
ADD (CONSTRAINT DEP_ID_PK PRIMARY KEY(DEPARTMENT_ID));

DELETE FROM DEPS
WHERE LOCATION_ID = 1400;

INSERT INTO DEPS(DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID)
VALUES(200, 'Human Resources', 2700);

UPDATE DEPS
SET DEPARTMENT_NAME = 'Operations'
WHERE DEPARTMENT_NAME = 'Administration';

UPDATE DEPS
SET DEPARTMENT_NAME = UPPER(DEPARTMENT_NAME);

ALTER TABLE DEPS
ADD (SECURITY_ID NUMBER(6));

UPDATE TABLE DEPS
SET SECURITY_ID = 101;

UPDATE DEPS
SET SECURITY_ID = 101;